//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minsk.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Minsk.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Diagnostic_UnterminatedString {
            get {
                return ResourceManager.GetString("Diagnostic_UnterminatedString", resourceCulture);
            }
        }
        
        internal static string Diagnostic_UnterminatedMultiLineComment {
            get {
                return ResourceManager.GetString("Diagnostic_UnterminatedMultiLineComment", resourceCulture);
            }
        }
        
        internal static string Diagnostic_UnexpectedToken {
            get {
                return ResourceManager.GetString("Diagnostic_UnexpectedToken", resourceCulture);
            }
        }
        
        internal static string Diagnostic_InvalidNumber {
            get {
                return ResourceManager.GetString("Diagnostic_InvalidNumber", resourceCulture);
            }
        }
        
        internal static string Diagnostic_BadCharacter {
            get {
                return ResourceManager.GetString("Diagnostic_BadCharacter", resourceCulture);
            }
        }
        
        internal static string Diagnostic_UndefinedUnaryOperator {
            get {
                return ResourceManager.GetString("Diagnostic_UndefinedUnaryOperator", resourceCulture);
            }
        }
        
        internal static string Diagnostic_UndefinedBinaryOperator {
            get {
                return ResourceManager.GetString("Diagnostic_UndefinedBinaryOperator", resourceCulture);
            }
        }
        
        internal static string Diagnostic_ParameterAlreadyDeclared {
            get {
                return ResourceManager.GetString("Diagnostic_ParameterAlreadyDeclared", resourceCulture);
            }
        }
        
        internal static string Diagnostic_UndefinedVariable {
            get {
                return ResourceManager.GetString("Diagnostic_UndefinedVariable", resourceCulture);
            }
        }
        
        internal static string Diagnostic_NotAVariable {
            get {
                return ResourceManager.GetString("Diagnostic_NotAVariable", resourceCulture);
            }
        }
        
        internal static string Diagnostic_UndefinedType {
            get {
                return ResourceManager.GetString("Diagnostic_UndefinedType", resourceCulture);
            }
        }
        
        internal static string Diagnostic_CannotConvert {
            get {
                return ResourceManager.GetString("Diagnostic_CannotConvert", resourceCulture);
            }
        }
        
        internal static string Diagnostic_CannotConvertImplicitly {
            get {
                return ResourceManager.GetString("Diagnostic_CannotConvertImplicitly", resourceCulture);
            }
        }
        
        internal static string Diagnostic_SymbolAlreadyDeclared {
            get {
                return ResourceManager.GetString("Diagnostic_SymbolAlreadyDeclared", resourceCulture);
            }
        }
        
        internal static string Diagnostic_CannotAssign {
            get {
                return ResourceManager.GetString("Diagnostic_CannotAssign", resourceCulture);
            }
        }
        
        internal static string Diagnostic_UndefinedFunction {
            get {
                return ResourceManager.GetString("Diagnostic_UndefinedFunction", resourceCulture);
            }
        }
        
        internal static string Diagnostic_NotAFunction {
            get {
                return ResourceManager.GetString("Diagnostic_NotAFunction", resourceCulture);
            }
        }
        
        internal static string Diagnostic_WrongArgumentCount {
            get {
                return ResourceManager.GetString("Diagnostic_WrongArgumentCount", resourceCulture);
            }
        }
        
        internal static string Diagnostic_ExpressionMustHaveValue {
            get {
                return ResourceManager.GetString("Diagnostic_ExpressionMustHaveValue", resourceCulture);
            }
        }
        
        internal static string Diagnostic_InvalidBreakOrContinue {
            get {
                return ResourceManager.GetString("Diagnostic_InvalidBreakOrContinue", resourceCulture);
            }
        }
        
        internal static string Diagnostic_AllPathsMustReturn {
            get {
                return ResourceManager.GetString("Diagnostic_AllPathsMustReturn", resourceCulture);
            }
        }
        
        internal static string Diagnostic_InvalidReturnExpression {
            get {
                return ResourceManager.GetString("Diagnostic_InvalidReturnExpression", resourceCulture);
            }
        }
        
        internal static string Diagnostic_InvalidReturnWithValueInGlobalStatements {
            get {
                return ResourceManager.GetString("Diagnostic_InvalidReturnWithValueInGlobalStatements", resourceCulture);
            }
        }
        
        internal static string Diagnostic_MissingReturnExpression {
            get {
                return ResourceManager.GetString("Diagnostic_MissingReturnExpression", resourceCulture);
            }
        }
        
        internal static string Diagnostic_InvalidExpressionStatement {
            get {
                return ResourceManager.GetString("Diagnostic_InvalidExpressionStatement", resourceCulture);
            }
        }
        
        internal static string Diagnostic_OnlyOneFileCanHaveGlobalStatements {
            get {
                return ResourceManager.GetString("Diagnostic_OnlyOneFileCanHaveGlobalStatements", resourceCulture);
            }
        }
        
        internal static string Diagnostic_UnreachableCode {
            get {
                return ResourceManager.GetString("Diagnostic_UnreachableCode", resourceCulture);
            }
        }
        
        internal static string Diagnostic_RequiredMethodNotFound {
            get {
                return ResourceManager.GetString("Diagnostic_RequiredMethodNotFound", resourceCulture);
            }
        }
        
        internal static string Diagnostic_RequiredTypeAmbiguousWithMinsk {
            get {
                return ResourceManager.GetString("Diagnostic_RequiredTypeAmbiguousWithMinsk", resourceCulture);
            }
        }
        
        internal static string Diagnostic_RequiredTypeAmbiguous {
            get {
                return ResourceManager.GetString("Diagnostic_RequiredTypeAmbiguous", resourceCulture);
            }
        }
        
        internal static string Diagnostic_RequiredTypeNotFound {
            get {
                return ResourceManager.GetString("Diagnostic_RequiredTypeNotFound", resourceCulture);
            }
        }
        
        internal static string Diagnostic_RequiredTypeNotFoundWithMinsk {
            get {
                return ResourceManager.GetString("Diagnostic_RequiredTypeNotFoundWithMinsk", resourceCulture);
            }
        }
        
        internal static string Diagnostic_InvalidReference {
            get {
                return ResourceManager.GetString("Diagnostic_InvalidReference", resourceCulture);
            }
        }
        
        internal static string Diagnostic_CannotMixMainAndGlobalStatements {
            get {
                return ResourceManager.GetString("Diagnostic_CannotMixMainAndGlobalStatements", resourceCulture);
            }
        }
        
        internal static string Diagnostic_MainMustHaveCorrectSignature {
            get {
                return ResourceManager.GetString("Diagnostic_MainMustHaveCorrectSignature", resourceCulture);
            }
        }
    }
}
