function main()
{
    let one = 1
    let two = 2
    
    print("1 + 2 =")
    print(string(one + two))
    
    print("1 * 2 =")
    print(string(one * two))
        
    print("1 - 2 =")
    print(string(one - two))
    
    print("1 / 2 =")
    print(string(one / two))
    
    print("1 + 1 * 2 =")
    print(string(one + one * two))
    
    print("(1 + 1) * 2 =")
    print(string((one + one) * two))
}